### ISSUE TITLE
Perform manual code scan for a part of the application (GitHub, Gerrit ...)

### ISSUE THREAD

**Issue by Nikola25** [BME-MIT-IET/IET-BARN-iet-2019#18]
The first step is planning.

**Comment by Nikola25** [comment]
The first step is planning.

**Comment by hareka777** [comment]
I think we should find some requirements.  We can classify the bugs and we can decide which categories should be fixed.

**Comment by Nikola25** [comment]
# Requirements
General: 
  [ ] The code works
  [ ] The code is easy to understand
  [ ] Follows coding conventions
  [ ] Names are simple and if possible short
  [ ] Names are spelt correctly
  [ ] Names contain units where applicable
  [ ] Enums are used instead of int constants where applicable
  [ ] There are no usages of 'magic numbers'
  [ ] All variables are in the smallest scope possible
  [ ] All class, variable, and method modifiers are correct.
  [ ] No System.out.println or similar calls exist
  [ ] Code is not repeated or duplicated
Documentation:
  [ ] All methods are commented in clear language.
  [ ] All edge cases are described in comments
  [ ] All unusual behaviour or edge case handling is commented
  [ ] Data structures and units of measurement are explained
Security:
  [ ] All data inputs are checked (for the correct type, length/size, format, and range)
  [ ] Invalid parameter values handled such that exceptions are not thrown
  [ ] No sensitive information is logged or visible in a stacktrace

**Comment by hareka777** [comment]
**"No System.out.println or similar calls exist"**
I would argue that we need this requirement, because we are testing the application and we need to know these information what we log by using System.out.println.

**Comment by hareka777** [comment]
We should use the SOLID principles as a requirement where possible, because it help us to make the code  more object oriented.

**Comment by Nikola25** [comment]
**"I would argue with that we need this requirement, because we are testing the application and we need to know these information what we log by using System.out.println."**
I agree, we demand it later.

**Comment by hareka777** [comment]
Can we agree that this issue can only be closed if we fixed all the bugs which violates the requirements?

**Comment by Nikola25** [comment]
Yes, I agree

**Comment by hareka777** [comment]
# Final Requirements
## General: 
  [ ] The code works
  [ ] The code is easy to understand
  [ ] Follows coding conventions
  [ ] Names are simple and if possible short
  [ ] Names are spelt correctly
  [ ] Names contain units where applicable
  [ ] Enums are used instead of int constants where applicable
  [ ] There are no usages of 'magic numbers'
  [ ] All variables are in the smallest scope possible
  [ ] All class, variable, and method modifiers are correct.
  [ ] SOLID principles
  [ ] Code is not repeated or duplicated
## Documentation:
  [ ] All methods are commented in clear language.
  [ ] All edge cases are described in comments
  [ ] All unusual behaviour or edge case handling is commented
  [ ] Data structures and units of measurement are explained
## Security:
  [ ] All data inputs are checked (for the correct type, length/size, format, and range)
  [ ] Invalid parameter values handled such that exceptions are not thrown
  [ ] No sensitive information is logged or visible in a stacktrace

**Comment by hareka777** [comment]
Final Requirements
General:
[ ] The code works
[ ] The code is easy to understand
[ ] Follows coding conventions
[ ] Names are simple and if possible short
[ ] Names are spelt correctly
[ ] Names contain units where applicable
[ ] Enums are used instead of int constants where applicable
[ ] There are no usages of 'magic numbers'
[ ] All variables are in the smallest scope possible
[ ] All class, variable, and method modifiers are correct.
[ ] SOLID principles
[ ] Code is not repeated or duplicated

Documentation:
[ ] All methods are commented in clear language.
[ ] All edge cases are described in comments
[ ] All unusual behaviour or edge case handling is commented
[ ] Data structures and units of measurement are explained

Security:
[ ] All data inputs are checked (for the correct type, length/size, format, and range)
[ ] Invalid parameter values handled such that exceptions are not thrown
[ ] No sensitive information is logged or visible in a stacktrace

**Comment by Nikola25** [comment]
Document to be reviewed:
Libraries/dotNetRDF/Compatibility/NO_WEB/HttpUtility.cs

**Comment by hareka777** [comment]
For me its okay.

**Comment by Nikola25** [comment]
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/blob/master/Libraries/dotNetRDF/Compatibility/NO_WEB/HttpUtility.cs

**Comment by hareka777** [comment]
Can we both review the whole class and then we split the fixing of the bugs what we will find?

**Comment by hareka777** [comment]
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/2940617a3bdc0fe260c04de3de02768090697de1#r33395497

**Comment by hareka777** [comment]
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/2940617a3bdc0fe260c04de3de02768090697de1#r33395561

**Comment by hareka777** [comment]
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/2940617a3bdc0fe260c04de3de02768090697de1#r33395646

**Comment by Nikola25** [comment]
**"Can we both review the whole class and then we split the fixing of the bugs what we will find?"**
I think I'll write comments for the second class and you write to the first class, then we exchange.
If we're ready, I'll fix the second class, you the first class. And I'll check for the first class repair, you the second class repair.

**Comment by hareka777** [comment]
Okay, and we can review each others' code.

**Comment by hareka777** [comment]
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/2940617a3bdc0fe260c04de3de02768090697de1#r33395718

**Comment by Nikola25** [comment]
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/2940617a3bdc0fe260c04de3de02768090697de1#r33395843

**Comment by Nikola25** [comment]
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/2940617a3bdc0fe260c04de3de02768090697de1#r33395905

**Comment by hareka777** [comment]
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/2940617a3bdc0fe260c04de3de02768090697de1#r33395497

**Comment by hareka777** [comment]
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/2940617a3bdc0fe260c04de3de02768090697de1#r33395561

**Comment by hareka777** [comment]
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/2940617a3bdc0fe260c04de3de02768090697de1#r33395718

**Comment by hareka777** [comment]
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/commit/2940617a3bdc0fe260c04de3de02768090697de1#r33395646

**Comment by Nikola25** [comment]
Repair in Libraries/dotNetRDF/Compatibility/NO_WEB/HttpUtility.cs
Pull Request: 
https://github.com/BME-MIT-IET/IET-BARN-iet-2019/pull/20#issue-275555675

**Comment by Nikola25** [comment]
Requirements
General:
[x] The code works
[x] The code is easy to understand
[x] Follows coding conventions
[x] Names are simple and if possible short
[x] Names are spelt correctly
[x] Names contain units where applicable
[x] Enums are used instead of int constants where applicable
[x] There are no usages of 'magic numbers'
[x] All variables are in the smallest scope possible
[x] All class, variable, and method modifiers are correct.
[x] SOLID principles
[x] Code is not repeated or duplicated
Documentation:
[x] All methods are commented in clear language.
[x] All edge cases are described in comments
[x] All unusual behaviour or edge case handling is commented
[x] Data structures and units of measurement are explained
Security:
[x] All data inputs are checked (for the correct type, length/size, format, and range)
[x] Invalid parameter values handled such that exceptions are not thrown
[x] No sensitive information is logged or visible in a stacktrace

**Comment by Nikola25** [comment]
We're ready, we've achieved our goal.
